### ISSUE TITLE
Add breakpoints/media queries mixins

### ISSUE THREAD

**Issue by lemoscaio** [devhatt/octopost#234]
# Feature description

[Mixins](https://sass-lang.com/documentation/at-rules/mixin/) and [functions](https://sass-lang.com/documentation/at-rules/function/) are good ways to wrap some code. With a breakpoint mixin, devs can reuse media queries with better syntax and control breakpoints with a single source of truth.

# Code Example 

This is just an example of using mixin, but there are other ways of doing so.  

### File: mixin.scss
```scss
$breakpoint-phone-only: 599px;

@mixin for-phone-only {
    @media (max-width: $breakpoint-phone-only) {
        @content;
    }
}
```

### File: style.scss 
```scss
@use "./../../styles/mixins.scss" as *;

.quick-questions-wrapper {
    display: flex;
    gap: 18px;
    flex-wrap: wrap;

    @include for-phone-only {
        flex-direction: column;
  }
}
```

### References with different examples of how to use it.

https://www.section.io/engineering-education/facilitating-css-media-queries-using-scss-mixins/
https://dev.to/rembertdesigns/how-to-write-media-queries-with-sass-mixins-32e
